### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Bed3viL** [kharyam/sdrplusplus-rpi#1]
Your install is the ONLY one that has actually worked on my Pi to get SDR++ installed. So first off,  HUGE thank you!

The current version of SDR++ used here is out of date.  There are currently some additional features in the more recent nightly build.  Would this be something that can be updated?

**Comment by kharyam** [comment]
Hi @Bed3viL - first of all, very cool that you found this repo and it works for you! The script is building from source based on the master branch, which will have all the latest changes. I checked and it looks like the nightly builds also come from the master branch. I'll update the script so that it pulls the latest code from the master branch just in case the clone has already run. Will ping you once I push it within the next hour or so.

**Comment by kharyam** [comment]
@Bed3viL I updated the script if you would like to give it a try.

**Comment by Bed3viL** [comment]
You sir, are amazing!   Thank you very much.  I am back in business.
